spring:
  application:
    name: tripmate-backend

  # 프로필 설정 (dev, prod 환경 분리)
  profiles:
    active: dev

  # MySQL 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tripmate?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234!@#$

    # PostgreSQL로 바꾸려면 위 3줄을 주석처리하고 아래 3줄 활성화:
    # driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/tripmate
    # username: postgres
    # password: your-password-here

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
      # create: 테이블 삭제 후 재생성 (데이터 다 날아감!)
      # update: 변경사항만 반영 (개발 시 추천)
      # validate: 스키마 검증만 (운영 시 추천)
      # none: 아무것도 안함
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        # PostgreSQL이면: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false  # OSIV 끄기 (성능 최적화)

  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /api  # 모든 API 앞에 /api 붙음
    encoding:
      charset: UTF-8
      force: true

# JWT 설정 (커스텀 프로퍼티)
jwt:
  secret: tripmate-super-secret-jwt-key-please-change-this-to-at-least-256-bits-long-random-string
  expiration: 604800000  # 7일 (밀리초 단위)

# 로깅 레벨
logging:
  level:
    root: INFO
    com.tripmate.backend: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


